DROP DATABASE IF EXISTS employeeDB;
CREATE DATABASE employeeDB;
USE employeeDB;

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT,
depName VARCHAR (30),
PRIMARY KEY (id)
);

CREATE TABLE empRole (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR (30) NOT NULL,
salary DECIMAL (7, 2) NOT NULL,
depID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
);

CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR (30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
roleID INT NOT NULL,
manID INT NOT NULL,
PRIMARY KEY (id)
);